### ISSUE TITLE
[BUG] - missing ListOptions namespace declaration causes library to crash

### ISSUE THREAD

**Issue by mercymantis** [vultr/vultr-php#4]
The namespace declaration for ListOptions is missing from /src/Services/VPC/VPCService.php and /src/Services/Firewall/FirewallService.php files which causes the library to crash when calling list methods.

This can be reproduced by calling $client->firewall->getFirewallGroups and $client->vpc->getVPCs

**Comment by Porthorian** [comment]
Thanks for reporting this issue mercy. Should be resolved, now
